# Generated by Django 5.2 on 2025-05-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="events/")),
                ("location", models.CharField(max_length=255)),
                ("event_day", models.CharField(max_length=2)),
                ("event_month", models.CharField(max_length=10)),
                ("time_range", models.CharField(max_length=50)),
            ],
        ),
    ]
