# Generated by Django 5.2 on 2025-05-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_day",
        ),
        migrations.RemoveField(
            model_name="event",
            name="event_month",
        ),
        migrations.RemoveField(
            model_name="event",
            name="time_range",
        ),
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
